import './globals.css';
import './bootstrap.min.css';
import Providers from '@/Providers';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className='py-3'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
